services:
  container1:
    build:
      context: .
      dockerfile: Dockerfile.container1
    container_name: container1
    ports:
      - "8081:8081" # javalin app port
      - "8082:8082" # websocket
    networks:
      - dad_network
    restart: unless-stopped

  container2:
    image: apache/activemq-artemis:latest
    container_name: container2-JMS-Topic-artemis
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - dad_network
    restart: unless-stopped
networks:
  dad_network:
# volumes:
#   mongo_data:
#   mysql_data:
volumes:
  artemis-data:
