services:
  artemis:
    image: apache/activemq-artemis:latest
    container_name: artemis-broker
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - "61616:61616"
      - "8161:8161"
    # volumes:
    #   - artemis-data:/var/lib/artemis
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: stud
      MONGO_INITDB_ROOT_PASSWORD: stud123
      MONGO_INITDB_DATABASE: snmpdb
    volumes:
      - ./data/mongo:/data/db
    restart: unless-stopped
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: stud123
      MYSQL_DATABASE: blobstore
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud123
    networks:
      - dad_network
    ports:
      - "3306:3306"

  snmp_agent:
    build:
      context: .
      dockerfile: Dockerfile.snmp
    container_name: snmp_agent
    ports:
      - "161:161/udp"
    networks:
      - dad_network
    restart: unless-stopped

  java_javalin:
    build: .
    container_name: java_javalin_app
    # amd 64 pentru a rula pe macos cu m1/m2
    platform: linux/amd64
    volumes:
      - ./apps/java:/usr/src/app
    ports:
      # este folosit de macos acest port, asa ca mapez 7001 de la 7000
      - "7001:7000"
    networks:
      - dad_network
    restart: unless-stopped
    depends_on:
      - artemis

  node-api:
    image: node:22.17
    container_name: node-api
    working_dir: /usr/src/app
    volumes:
      - ./apps/node-api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: npm start
    restart: unless-stopped
    networks:
      - dad_network

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: react-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/apps/react-app
      - /apps/react-app/node_modules
    restart: unless-stopped

  node_api:
    build: .
    container_name: node_api_app
    volumes:
      - ./apps/node_api:/usr/src/app
    ports:
      - "8080:8080"
    networks:
      - dad_network
    restart: unless-stopped

networks:
  dad_network:
# volumes:
#   mongo_data:
#   mysql_data:
volumes:
  artemis-data:
