services:
  container1:
    build:
      context: .
      dockerfile: Dockerfile.container1
    container_name: container1
    ports:
      - "8081:8081" # javalin app port
      - "8082:8082" # websocket
    networks:
      - dad_network
    restart: unless-stopped

  container2:
    image: apache/activemq-artemis:latest
    container_name: container2-JMS-Topic-artemis
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - dad_network
    restart: unless-stopped

  # REST API in node.js w MongoDB with 2 REST API endpoints interfaces: 1 for DB access and 1 for Web Access
  container6:
    build:
      context: .
      dockerfile: Dockerfile.container6
    container_name: container6
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://stud:stud123@mongo:27017/snmpdb?authSource=admin
      - DB_HOST=mysql
      - DB_USER=stud
      - DB_PASSWORD=stud123
      - DB_NAME=blobstore
      - SNMP_TARGET_IP=snmp_agent
      - SNMP_COMMUNITY=public
    depends_on:
      - mongo
      - mysql
    networks:
      - dad_network
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: stud
      MONGO_INITDB_ROOT_PASSWORD: stud123
      MONGO_INITDB_DATABASE: snmpdb
    volumes:
      - ./data/mongo:/data/db
    networks:
      - dad_network
    restart: unless-stopped
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: stud123
      MYSQL_DATABASE: blobstore
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud123
    networks:
      - dad_network
    ports:
      - "3306:3306"

networks:
  dad_network:
# volumes:
#   mongo_data:
#   mysql_data:
volumes:
  artemis-data:
